const { db } = require('./config');

async function ensureHostTables() {
  const client = await db.connect();

  try {
    await client.query('BEGIN');
    await client.query(`
      CREATE TABLE IF NOT EXISTS public.host (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        player_id INTEGER,
        display_name TEXT NOT NULL CHECK (btrim(display_name) <> ''),
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT host_pkey PRIMARY KEY (id),
        CONSTRAINT host_player_id_key UNIQUE (player_id),
        CONSTRAINT host_player_id_fkey
          FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE SET NULL
      )
    `);
    await client.query(`
      CREATE TABLE IF NOT EXISTS public.host_bank_accounts (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY,
        host_id INTEGER NOT NULL,
        label TEXT,
        bank_bin TEXT NOT NULL CHECK (bank_bin ~ '^[0-9]{6}$'),
        bank_name TEXT,
        account_number TEXT NOT NULL CHECK (account_number ~ '^[A-Za-z0-9]{1,19}$'),
        account_name TEXT NOT NULL CHECK (btrim(account_name) <> ''),
        is_active BOOLEAN NOT NULL DEFAULT TRUE,
        is_default BOOLEAN NOT NULL DEFAULT FALSE CHECK (NOT is_default OR is_active),
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
        CONSTRAINT host_bank_accounts_pkey PRIMARY KEY (id),
        CONSTRAINT host_bank_accounts_host_bank_account_key
          UNIQUE (host_id, bank_bin, account_number),
        CONSTRAINT host_bank_accounts_host_id_fkey
          FOREIGN KEY (host_id) REFERENCES public.host(id) ON DELETE RESTRICT
      )
    `);
    await client.query(`
      CREATE UNIQUE INDEX IF NOT EXISTS host_bank_accounts_one_default_per_host_idx
      ON public.host_bank_accounts (host_id) WHERE is_default
    `);
    await client.query('ALTER TABLE public.host ENABLE ROW LEVEL SECURITY');
    await client.query(
      'ALTER TABLE public.host_bank_accounts ENABLE ROW LEVEL SECURITY'
    );

    const { rows } = await client.query(
      "SELECT rolname FROM pg_roles WHERE rolname IN ('anon', 'authenticated')"
    );
    const roles = new Set(rows.map(row => row.rolname));

    for (const role of ['anon', 'authenticated']) {
      if (!roles.has(role)) continue;
      await client.query(
        `REVOKE ALL PRIVILEGES ON TABLE public.host, public.host_bank_accounts FROM ${role}`
      );
      await client.query(
        `REVOKE ALL PRIVILEGES ON SEQUENCE public.host_id_seq, public.host_bank_accounts_id_seq FROM ${role}`
      );
    }

    await client.query('COMMIT');
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}

module.exports = { ensureHostTables };
