-- Executable PostgreSQL schema for a fresh Supabase project.
--
-- This schema matches the ChiaTeam API and the required production constraints.
-- Run it once in Supabase Dashboard -> SQL Editor on an empty project.
-- The API connects with DATABASE_URL as the postgres role, so direct Data API
-- access for anon/authenticated roles is disabled at the end of this file.

BEGIN;

CREATE TABLE public.players (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint NOT NULL,
  number integer NOT NULL,
  name text NOT NULL,
  username text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  avatar text,
  CONSTRAINT players_pkey PRIMARY KEY (id),
  CONSTRAINT players_user_id_key UNIQUE (user_id)
);

CREATE TABLE public.host (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  player_id integer,
  display_name text NOT NULL CHECK (btrim(display_name) <> ''),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT host_pkey PRIMARY KEY (id),
  CONSTRAINT host_player_id_key UNIQUE (player_id),
  CONSTRAINT host_player_id_fkey
    FOREIGN KEY (player_id) REFERENCES public.players(id) ON DELETE SET NULL
);

CREATE TABLE public.host_bank_accounts (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  host_id integer NOT NULL,
  label text,
  bank_bin text NOT NULL CHECK (bank_bin ~ '^[0-9]{6}$'),
  bank_name text,
  account_number text NOT NULL CHECK (account_number ~ '^[A-Za-z0-9]{1,19}$'),
  account_name text NOT NULL CHECK (btrim(account_name) <> ''),
  is_active boolean NOT NULL DEFAULT true,
  is_default boolean NOT NULL DEFAULT false CHECK (NOT is_default OR is_active),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT host_bank_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT host_bank_accounts_host_bank_account_key
    UNIQUE (host_id, bank_bin, account_number),
  CONSTRAINT host_bank_accounts_host_id_fkey
    FOREIGN KEY (host_id) REFERENCES public.host(id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX host_bank_accounts_one_default_per_host_idx
  ON public.host_bank_accounts (host_id) WHERE is_default;

CREATE TABLE public.fee_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bill_date date NOT NULL UNIQUE,
  source_hash text NOT NULL,
  account_id integer NOT NULL REFERENCES public.host_bank_accounts(id) ON DELETE RESTRICT,
  account_snapshot jsonb NOT NULL,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.fee_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id bigint NOT NULL REFERENCES public.fee_batches(id) ON DELETE RESTRICT,
  request_index integer NOT NULL,
  telegram_user_id bigint NOT NULL CHECK (telegram_user_id > 0),
  display_name text NOT NULL,
  team text NOT NULL CHECK (team IN ('HOME', 'AWAY')),
  amount integer NOT NULL CHECK (amount > 0),
  transfer_note text NOT NULL UNIQUE,
  delivery_status text NOT NULL DEFAULT 'pending'
    CHECK (delivery_status IN ('pending', 'sending', 'sent', 'failed')),
  telegram_message_id bigint,
  delivery_error text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (batch_id, telegram_user_id),
  UNIQUE (batch_id, request_index)
);

CREATE TABLE public.matches (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  match_date date NOT NULL,
  san text,
  tiensan integer,
  home_score integer,
  away_score integer,
  winner_side text CHECK (winner_side IS NULL OR winner_side = ANY (ARRAY['HOME', 'AWAY'])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT matches_pkey PRIMARY KEY (id),
  CONSTRAINT matches_match_date_key UNIQUE (match_date)
);

CREATE TABLE public.match_players (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  match_id integer NOT NULL,
  player_id integer,
  user_id bigint,
  side text NOT NULL,
  display_name text,
  CONSTRAINT match_players_pkey PRIMARY KEY (id),
  CONSTRAINT match_players_match_id_fkey
    FOREIGN KEY (match_id) REFERENCES public.matches(id) ON DELETE CASCADE,
  CONSTRAINT match_players_player_id_fkey
    FOREIGN KEY (player_id) REFERENCES public.players(id)
);

CREATE TABLE public.match_player_stats (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  match_id integer NOT NULL,
  player_id integer NOT NULL,
  goals integer DEFAULT 0,
  assists integer DEFAULT 0,
  is_mvp integer DEFAULT 0,
  result text CHECK (result IS NULL OR result = ANY (ARRAY['WIN', 'LOSE'])),
  CONSTRAINT match_player_stats_pkey PRIMARY KEY (id),
  CONSTRAINT match_player_stats_match_id_player_id_key
    UNIQUE (match_id, player_id),
  CONSTRAINT match_player_stats_match_id_fkey
    FOREIGN KEY (match_id) REFERENCES public.matches(id) ON DELETE CASCADE,
  CONSTRAINT match_player_stats_player_id_fkey
    FOREIGN KEY (player_id) REFERENCES public.players(id)
);

CREATE TABLE public.world_cup_prediction_matches (
  id text NOT NULL,
  match_number integer,
  match_date date NOT NULL,
  match_time time without time zone NOT NULL,
  home_team text NOT NULL,
  away_team text NOT NULL,
  status text NOT NULL DEFAULT 'OPEN',
  result smallint CHECK (result = ANY (ARRAY[0, 1, 2])),
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  home_score smallint CHECK (home_score IS NULL OR home_score >= 0),
  away_score smallint CHECK (away_score IS NULL OR away_score >= 0),
  CONSTRAINT world_cup_prediction_matches_pkey PRIMARY KEY (id),
  CONSTRAINT world_cup_prediction_matches_match_number_key UNIQUE (match_number)
);

CREATE TABLE public.world_cup_prediction_members (
  member_id text NOT NULL,
  name text NOT NULL,
  access_key character(6) NOT NULL,
  revoked_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  username text,
  CONSTRAINT world_cup_prediction_members_pkey PRIMARY KEY (member_id),
  CONSTRAINT world_cup_prediction_members_access_key_key UNIQUE (access_key)
);

CREATE TABLE public.world_cup_predictions (
  match_id text NOT NULL,
  member_id text NOT NULL,
  prediction smallint NOT NULL CHECK (prediction = ANY (ARRAY[0, 1, 2])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT world_cup_predictions_pkey PRIMARY KEY (match_id, member_id),
  CONSTRAINT world_cup_predictions_match_id_fkey
    FOREIGN KEY (match_id)
    REFERENCES public.world_cup_prediction_matches(id)
    ON DELETE CASCADE,
  CONSTRAINT world_cup_predictions_member_id_fkey
    FOREIGN KEY (member_id)
    REFERENCES public.world_cup_prediction_members(member_id)
    ON DELETE CASCADE
);

CREATE TABLE public.storage (
  id smallint NOT NULL,
  bench jsonb,
  "teamA" jsonb,
  "teamB" jsonb,
  "team3A" jsonb,
  "team3B" jsonb,
  "team3C" jsonb,
  manifest jsonb,
  san text,
  tiensan integer,
  tiennuoc integer,
  "teamThua" text,
  "activeVote" jsonb,
  "lastUpdated" text,
  CONSTRAINT storage_pkey PRIMARY KEY (id),
  CONSTRAINT storage_id_check CHECK (id = 1)
);

CREATE TABLE public.bot_controls (
  platform text PRIMARY KEY CHECK (platform IN ('telegram', 'zalo')),
  commands_enabled boolean NOT NULL DEFAULT true,
  last_command_at timestamp with time zone,
  mode text CHECK (mode IN ('polling', 'webhook')),
  updated_at timestamp with time zone
);

CREATE TABLE public.current_match (
  id smallint NOT NULL,
  active_vote jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT current_match_pkey PRIMARY KEY (id),
  CONSTRAINT current_match_id_check CHECK (id = 1)
);

CREATE TABLE public.webhook_events (
  platform text NOT NULL,
  event_id text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['processing', 'completed'])),
  claim_id text,
  lease_expires_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT webhook_events_pkey PRIMARY KEY (platform, event_id)
);

CREATE INDEX webhook_events_expiry_idx
  ON public.webhook_events (expires_at);

CREATE TABLE public.zalo_greetings (
  user_id text PRIMARY KEY,
  chat_id text NOT NULL,
  claimed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.zalo_announcement_subscriptions (
  chat_id text PRIMARY KEY,
  user_id text NOT NULL UNIQUE,
  display_name text,
  subscribed boolean NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.zalo_announcements (
  id uuid PRIMARY KEY,
  actor_id text NOT NULL,
  source_chat_id text NOT NULL,
  source_thread_id text NOT NULL,
  message text NOT NULL,
  photo_url text,
  status text NOT NULL CHECK (status IN ('draft', 'sending', 'finished', 'cancelled')),
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT zalo_announcements_content_check CHECK (
    char_length(message) BETWEEN 0 AND 2000 AND (photo_url IS NOT NULL OR char_length(message) BETWEEN 1 AND 2000)
  )
);

CREATE TABLE public.zalo_announcement_deliveries (
  announcement_id uuid NOT NULL REFERENCES public.zalo_announcements(id),
  chat_id text NOT NULL,
  user_id text NOT NULL,
  status text NOT NULL CHECK (status IN ('pending', 'sending', 'sent', 'failed', 'unknown', 'skipped')),
  error_code text,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (announcement_id, chat_id)
);

CREATE TABLE public.match_video_sources (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  match_id integer NOT NULL,
  slot smallint NOT NULL CHECK (slot = ANY (ARRAY[1, 2])),
  provider text NOT NULL DEFAULT 'youtube' CHECK (provider = 'youtube'),
  video_id text NOT NULL,
  source_url text NOT NULL,
  title text,
  offset_seconds integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT match_video_sources_pkey PRIMARY KEY (id),
  CONSTRAINT match_video_sources_match_id_slot_key UNIQUE (match_id, slot),
  CONSTRAINT match_video_sources_match_id_fkey
    FOREIGN KEY (match_id) REFERENCES public.matches(id) ON DELETE CASCADE
);

CREATE TABLE public.match_highlights (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  match_id integer NOT NULL,
  timestamp_seconds integer NOT NULL CHECK (timestamp_seconds >= 0),
  caption text NOT NULL,
  preferred_source_slot smallint CHECK (
    preferred_source_slot IS NULL OR preferred_source_slot = ANY (ARRAY[1, 2])
  ),
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT match_highlights_pkey PRIMARY KEY (id),
  CONSTRAINT match_highlights_match_id_fkey
    FOREIGN KEY (match_id) REFERENCES public.matches(id) ON DELETE CASCADE
);

CREATE INDEX match_highlights_timeline_idx
  ON public.match_highlights (match_id, timestamp_seconds, id);

CREATE TABLE public.video_2nikes (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  video_id text NOT NULL,
  title text NOT NULL,
  timestamp_seconds integer NOT NULL CHECK (
    timestamp_seconds >= 0 AND timestamp_seconds <= 86400
  ),
  created_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT video_2nikes_pkey PRIMARY KEY (id)
);

CREATE INDEX video_2nikes_timeline_idx
  ON public.video_2nikes (video_id, timestamp_seconds, id);

-- The API uses a trusted PostgreSQL connection instead of Supabase Data API.
-- Keep these tables unavailable through public anon/authenticated API roles.
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.host ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.host_bank_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fee_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_player_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.world_cup_prediction_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.world_cup_prediction_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.world_cup_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.storage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bot_controls ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.current_match ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zalo_announcement_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zalo_greetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zalo_announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.zalo_announcement_deliveries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_video_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_highlights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.video_2nikes ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE
  public.players,
  public.host,
  public.host_bank_accounts,
  public.fee_batches,
  public.fee_requests,
  public.matches,
  public.match_players,
  public.match_player_stats,
  public.world_cup_prediction_matches,
  public.world_cup_prediction_members,
  public.world_cup_predictions,
  public.storage,
  public.bot_controls,
  public.current_match,
  public.webhook_events,
  public.zalo_announcement_subscriptions,
  public.zalo_greetings,
  public.zalo_announcements,
  public.zalo_announcement_deliveries,
  public.match_video_sources,
  public.match_highlights,
  public.video_2nikes
FROM anon, authenticated;

REVOKE ALL PRIVILEGES ON SEQUENCE
  public.players_id_seq,
  public.host_id_seq,
  public.host_bank_accounts_id_seq,
  public.fee_batches_id_seq,
  public.fee_requests_id_seq,
  public.matches_id_seq,
  public.match_players_id_seq,
  public.match_player_stats_id_seq,
  public.match_video_sources_id_seq,
  public.match_highlights_id_seq,
  public.video_2nikes_id_seq
FROM anon, authenticated;

-- Prevent future tables and sequences created by postgres from receiving the
-- broad default Supabase API grants automatically.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON SEQUENCES FROM anon, authenticated;

COMMIT;
