-- Executable PostgreSQL schema for a fresh Supabase project.
--
-- This schema matches the ChiaTeam API and the required production constraints.
-- Run it once in Supabase Dashboard -> SQL Editor on an empty project.
-- The API connects with DATABASE_URL as the postgres role, so direct Data API
-- access for anon/authenticated roles is disabled at the end of this file.

BEGIN;

CREATE TABLE public.leaderboard (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  player_number integer NOT NULL,
  total_match integer DEFAULT 0,
  total_win integer DEFAULT 0,
  total_lose integer DEFAULT 0,
  total_draw integer DEFAULT 0,
  winrate double precision DEFAULT 0.0,
  goal integer DEFAULT 0,
  assist integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leaderboard_pkey PRIMARY KEY (id),
  CONSTRAINT leaderboard_player_number_key UNIQUE (player_number)
);

CREATE TABLE public.players (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  user_id bigint NOT NULL,
  number integer NOT NULL,
  name text NOT NULL,
  username text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  avatar text,
  CONSTRAINT players_pkey PRIMARY KEY (id),
  CONSTRAINT players_user_id_key UNIQUE (user_id)
);

CREATE TABLE public.matches (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  match_date date NOT NULL,
  san text,
  tiensan integer,
  home_score integer,
  away_score integer,
  winner_side text CHECK (winner_side IS NULL OR winner_side = ANY (ARRAY['HOME', 'AWAY'])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT matches_pkey PRIMARY KEY (id),
  CONSTRAINT matches_match_date_key UNIQUE (match_date)
);

CREATE TABLE public.match_players (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  match_id integer NOT NULL,
  player_id integer,
  user_id bigint,
  side text NOT NULL,
  display_name text,
  CONSTRAINT match_players_pkey PRIMARY KEY (id),
  CONSTRAINT match_players_match_id_fkey
    FOREIGN KEY (match_id) REFERENCES public.matches(id) ON DELETE CASCADE,
  CONSTRAINT match_players_player_id_fkey
    FOREIGN KEY (player_id) REFERENCES public.players(id)
);

CREATE TABLE public.match_player_stats (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  match_id integer NOT NULL,
  player_id integer NOT NULL,
  goals integer DEFAULT 0,
  assists integer DEFAULT 0,
  is_mvp integer DEFAULT 0,
  result text CHECK (result IS NULL OR result = ANY (ARRAY['WIN', 'LOSE'])),
  CONSTRAINT match_player_stats_pkey PRIMARY KEY (id),
  CONSTRAINT match_player_stats_match_id_player_id_key
    UNIQUE (match_id, player_id),
  CONSTRAINT match_player_stats_match_id_fkey
    FOREIGN KEY (match_id) REFERENCES public.matches(id) ON DELETE CASCADE,
  CONSTRAINT match_player_stats_player_id_fkey
    FOREIGN KEY (player_id) REFERENCES public.players(id)
);

CREATE TABLE public.world_cup_prediction_matches (
  id text NOT NULL,
  match_number integer,
  match_date date NOT NULL,
  match_time time without time zone NOT NULL,
  home_team text NOT NULL,
  away_team text NOT NULL,
  status text NOT NULL DEFAULT 'OPEN',
  result smallint CHECK (result = ANY (ARRAY[0, 1, 2])),
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  home_score smallint CHECK (home_score IS NULL OR home_score >= 0),
  away_score smallint CHECK (away_score IS NULL OR away_score >= 0),
  CONSTRAINT world_cup_prediction_matches_pkey PRIMARY KEY (id),
  CONSTRAINT world_cup_prediction_matches_match_number_key UNIQUE (match_number)
);

CREATE TABLE public.world_cup_prediction_members (
  member_id text NOT NULL,
  name text NOT NULL,
  access_key character(6) NOT NULL,
  revoked_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  username text,
  CONSTRAINT world_cup_prediction_members_pkey PRIMARY KEY (member_id),
  CONSTRAINT world_cup_prediction_members_access_key_key UNIQUE (access_key)
);

CREATE TABLE public.world_cup_predictions (
  match_id text NOT NULL,
  member_id text NOT NULL,
  prediction smallint NOT NULL CHECK (prediction = ANY (ARRAY[0, 1, 2])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT world_cup_predictions_pkey PRIMARY KEY (match_id, member_id),
  CONSTRAINT world_cup_predictions_match_id_fkey
    FOREIGN KEY (match_id)
    REFERENCES public.world_cup_prediction_matches(id)
    ON DELETE CASCADE,
  CONSTRAINT world_cup_predictions_member_id_fkey
    FOREIGN KEY (member_id)
    REFERENCES public.world_cup_prediction_members(member_id)
    ON DELETE CASCADE
);

CREATE TABLE public.storage (
  id smallint NOT NULL,
  bench jsonb,
  "teamA" jsonb,
  "teamB" jsonb,
  "team3A" jsonb,
  "team3B" jsonb,
  "team3C" jsonb,
  manifest jsonb,
  san text,
  tiensan integer,
  tiennuoc integer,
  "teamThua" text,
  "activeVote" jsonb,
  "lastUpdated" text,
  CONSTRAINT storage_pkey PRIMARY KEY (id),
  CONSTRAINT storage_id_check CHECK (id = 1)
);

CREATE TABLE public.current_match (
  id smallint NOT NULL,
  active_vote jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT current_match_pkey PRIMARY KEY (id),
  CONSTRAINT current_match_id_check CHECK (id = 1)
);

CREATE TABLE public.webhook_events (
  platform text NOT NULL,
  event_id text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['processing', 'completed'])),
  claim_id text,
  lease_expires_at timestamp with time zone,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT webhook_events_pkey PRIMARY KEY (platform, event_id)
);

CREATE INDEX webhook_events_expiry_idx
  ON public.webhook_events (expires_at);

CREATE TABLE public.match_video_sources (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  match_id integer NOT NULL,
  slot smallint NOT NULL CHECK (slot = ANY (ARRAY[1, 2])),
  provider text NOT NULL DEFAULT 'youtube' CHECK (provider = 'youtube'),
  video_id text NOT NULL,
  source_url text NOT NULL,
  title text,
  offset_seconds integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT match_video_sources_pkey PRIMARY KEY (id),
  CONSTRAINT match_video_sources_match_id_slot_key UNIQUE (match_id, slot),
  CONSTRAINT match_video_sources_match_id_fkey
    FOREIGN KEY (match_id) REFERENCES public.matches(id) ON DELETE CASCADE
);

CREATE TABLE public.match_highlights (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  match_id integer NOT NULL,
  timestamp_seconds integer NOT NULL CHECK (timestamp_seconds >= 0),
  caption text NOT NULL,
  preferred_source_slot smallint CHECK (
    preferred_source_slot IS NULL OR preferred_source_slot = ANY (ARRAY[1, 2])
  ),
  created_by text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT match_highlights_pkey PRIMARY KEY (id),
  CONSTRAINT match_highlights_match_id_fkey
    FOREIGN KEY (match_id) REFERENCES public.matches(id) ON DELETE CASCADE
);

CREATE INDEX match_highlights_timeline_idx
  ON public.match_highlights (match_id, timestamp_seconds, id);

CREATE TABLE public.video_2nikes (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  video_id text NOT NULL,
  title text NOT NULL,
  timestamp_seconds integer NOT NULL CHECK (
    timestamp_seconds >= 0 AND timestamp_seconds <= 86400
  ),
  created_by text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT video_2nikes_pkey PRIMARY KEY (id)
);

CREATE INDEX video_2nikes_timeline_idx
  ON public.video_2nikes (video_id, timestamp_seconds, id);

-- The API uses a trusted PostgreSQL connection instead of Supabase Data API.
-- Keep these tables unavailable through public anon/authenticated API roles.
ALTER TABLE public.leaderboard ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_player_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.world_cup_prediction_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.world_cup_prediction_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.world_cup_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.storage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.current_match ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.webhook_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_video_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_highlights ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.video_2nikes ENABLE ROW LEVEL SECURITY;

REVOKE ALL PRIVILEGES ON TABLE
  public.leaderboard,
  public.players,
  public.matches,
  public.match_players,
  public.match_player_stats,
  public.world_cup_prediction_matches,
  public.world_cup_prediction_members,
  public.world_cup_predictions,
  public.storage,
  public.current_match,
  public.webhook_events,
  public.match_video_sources,
  public.match_highlights,
  public.video_2nikes
FROM anon, authenticated;

REVOKE ALL PRIVILEGES ON SEQUENCE
  public.leaderboard_id_seq,
  public.players_id_seq,
  public.matches_id_seq,
  public.match_players_id_seq,
  public.match_player_stats_id_seq,
  public.match_video_sources_id_seq,
  public.match_highlights_id_seq,
  public.video_2nikes_id_seq
FROM anon, authenticated;

-- Prevent future tables and sequences created by postgres from receiving the
-- broad default Supabase API grants automatically.
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON TABLES FROM anon, authenticated;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public
  REVOKE ALL ON SEQUENCES FROM anon, authenticated;

COMMIT;
