const entries = [
  [
    'TELEGRAM_BOT_TOKEN',
    'Telegram',
    'Telegram bot token',
    'Mã token bot Telegram',
    'secret',
    ['telegram'],
    'restart',
  ],
  [
    'BOT_OWNER_ID',
    'Telegram',
    'Telegram owner ID',
    'ID chủ bot Telegram',
    'text',
    ['telegram'],
    'restart',
  ],
  [
    'BOT_ADMIN_IDS',
    'Telegram',
    'Telegram admin IDs',
    'Danh sách ID quản trị Telegram',
    'text',
    ['telegram'],
    'restart',
  ],
  [
    'CHAT_ID',
    'Telegram',
    'Group chat ID',
    'ID nhóm Telegram (nơi bot nhận và gửi tin)',
    'text',
    ['telegram'],
    'restart',
  ],
  [
    'DEFAULT_THREAD_ID',
    'Telegram',
    'Default topic ID',
    'ID topic mặc định (message_thread_id trong nhóm)',
    'text',
    ['telegram'],
    'restart',
  ],
  [
    'MAIN_THREAD_ID',
    'Telegram',
    'Main topic ID',
    'ID topic chính (message_thread_id trong nhóm)',
    'text',
    ['telegram'],
    'restart',
  ],
  [
    'ANNOUNCEMENT_THREAD_ID',
    'Telegram',
    'Announcement topic ID',
    'ID topic thông báo (message_thread_id, khác với ID nhóm)',
    'text',
    ['telegram'],
    'restart',
  ],
  [
    'VIP_THREAD_ID',
    'Telegram',
    'VIP topic ID',
    'ID topic VIP (message_thread_id trong nhóm)',
    'text',
    ['telegram'],
    'restart',
  ],
  [
    'STATISTICS_THREAD_ID',
    'Telegram',
    'Statistics topic ID',
    'ID topic thống kê (message_thread_id trong nhóm)',
    'text',
    ['telegram'],
    'restart',
  ],
  [
    'ZALO_BOT_TOKEN',
    'Zalo',
    'Zalo bot token',
    'Mã token bot Zalo',
    'secret',
    ['zalo-polling', 'zalo-webhook', 'telegram'],
    'restart',
  ],
  [
    'ZALO_BOT_OWNER_ID',
    'Zalo',
    'Zalo owner ID',
    'ID chủ bot Zalo',
    'text',
    ['zalo-polling', 'zalo-webhook'],
    'restart',
  ],
  [
    'ZALO_BOT_ADMIN_IDS',
    'Zalo',
    'Zalo admin IDs',
    'Danh sách ID quản trị Zalo',
    'text',
    ['zalo-polling', 'zalo-webhook'],
    'restart',
  ],
  [
    'ZALO_MODE',
    'Zalo',
    'Zalo delivery mode',
    'Chế độ nhận tin Zalo',
    'enum',
    ['zalo-polling', 'zalo-webhook'],
    'deployment',
    { options: ['polling', 'webhook'], default: 'polling' },
  ],
  [
    'ZALO_WEBHOOK_URL',
    'Zalo',
    'Zalo webhook URL',
    'Địa chỉ webhook Zalo',
    'url',
    ['zalo-webhook'],
    'deployment',
  ],
  [
    'ZALO_WEBHOOK_SECRET',
    'Zalo',
    'Zalo webhook secret',
    'Mã bảo mật webhook Zalo',
    'secret',
    ['zalo-webhook'],
    'deployment',
  ],
  [
    'ZALO_GREETING_ENABLED',
    'Zalo',
    'Greeting enabled',
    'Bật lời chào Zalo',
    'boolean',
    ['zalo-polling', 'zalo-webhook'],
    'request',
    { default: true },
  ],
  [
    'ZALO_GREETING_TEXT',
    'Zalo',
    'Greeting text',
    'Nội dung lời chào Zalo',
    'text',
    ['zalo-polling', 'zalo-webhook'],
    'request',
  ],
  [
    'INTERNAL_API_AUTH_TOKEN',
    'API',
    'Internal API token',
    'Mã xác thực API nội bộ',
    'secret',
    ['api', 'admin', 'telegram', 'zalo-polling', 'zalo-webhook'],
    'restart',
  ],
  [
    'DATABASE_URL',
    'API',
    'Match database URL',
    'Địa chỉ cơ sở dữ liệu trận đấu',
    'secret',
    ['api', 'telegram', 'zalo-polling', 'zalo-webhook'],
    'deployment',
  ],
  [
    'SUPABASE_URL',
    'Storage',
    'Supabase URL',
    'Địa chỉ Supabase',
    'url',
    ['api', 'zalo-polling', 'zalo-webhook'],
    'deployment',
  ],
  [
    'SUPABASE_SERVICE_ROLE_KEY',
    'Storage',
    'Supabase service key',
    'Mã dịch vụ Supabase',
    'secret',
    ['api', 'zalo-polling', 'zalo-webhook'],
    'deployment',
  ],
  [
    'SUPABASE_STORAGE_BUCKET',
    'Storage',
    'Avatar storage bucket',
    'Bucket ảnh đại diện',
    'text',
    ['api'],
    'request',
  ],
  [
    'SUPABASE_ZALO_STORAGE_BUCKET',
    'Storage',
    'Zalo image bucket',
    'Bucket ảnh Zalo',
    'text',
    ['api', 'zalo-polling', 'zalo-webhook'],
    'request',
  ],
  [
    'GEMINI_API_KEY',
    'AI',
    'Gemini API key',
    'Mã API Gemini',
    'secret',
    ['api'],
    'restart',
  ],
  [
    'MAINTENANCE_MODE',
    'Runtime',
    'Maintenance mode',
    'Chế độ bảo trì',
    'boolean',
    ['api', 'telegram'],
    'restart',
  ],
  [
    'MAINTENANCE_UNTIL',
    'Runtime',
    'Maintenance end time',
    'Thời điểm kết thúc bảo trì',
    'text',
    ['api', 'telegram'],
    'restart',
  ],
  [
    'DEBUG_LOGGING',
    'Runtime',
    'Debug logging',
    'Ghi log chi tiết',
    'boolean',
    ['api', 'telegram', 'zalo-polling', 'zalo-webhook'],
    'restart',
  ],
  [
    'ADMIN_UI_URL',
    'Deployment',
    'Admin UI URL',
    'Địa chỉ giao diện quản trị',
    'url',
    ['admin'],
    'deployment',
  ],
  [
    'WEB_UI_URL',
    'Deployment',
    'Web UI URL',
    'Địa chỉ giao diện người dùng',
    'url',
    ['api'],
    'deployment',
  ],
  [
    'ADMIN_API_URL',
    'Deployment',
    'Admin API URL',
    'Địa chỉ API quản trị',
    'url',
    ['admin'],
    'deployment',
  ],
  [
    'TELEGRAM_API_URL',
    'Deployment',
    'Telegram API URL',
    'Địa chỉ API nội bộ Telegram',
    'url',
    ['telegram'],
    'deployment',
  ],
  [
    'ZALO_API_URL',
    'Deployment',
    'Zalo API URL',
    'Địa chỉ API nội bộ Zalo',
    'url',
    ['zalo-polling', 'zalo-webhook'],
    'deployment',
  ],
  [
    'API_PORT',
    'Deployment',
    'API port',
    'Cổng API',
    'number',
    ['api'],
    'deployment',
  ],
  [
    'BOT_COMMAND_PREFIX',
    'Commands',
    'Bot command prefix',
    'Tiền tố lệnh bot',
    'text',
    ['telegram', 'zalo-polling', 'zalo-webhook'],
    'request',
  ],
  [
    'TELEGRAM_COMMAND_RULES',
    'Commands',
    'Telegram command rules',
    'Quy tắc lệnh Telegram',
    'json',
    ['telegram'],
    'request',
  ],
  [
    'ZALO_COMMAND_RULES',
    'Commands',
    'Zalo command rules',
    'Quy tắc lệnh Zalo',
    'json',
    ['zalo-polling', 'zalo-webhook'],
    'request',
  ],
];
const BOOTSTRAP = [
  ...['BOT_API_BASE_URL', 'API_INTERNAL_URL', 'API_BASE_URL', 'API_URL'].map(
    key => [
      key,
      key,
      key,
      'Legacy startup alias. Imported into the three managed API addresses on first setup; edit those addresses afterwards.',
      'Tên cấu hình khởi động cũ. Nhập vào ba địa chỉ API khi thiết lập lần đầu; sau đó sửa các địa chỉ riêng.',
    ]
  ),
  ...['PORT', 'UI_API_PORT'].map(key => [
    key,
    key,
    key,
    'Hosting port alias. API_PORT is the managed value; keep the Railway target port aligned.',
    'Tên cổng của máy chủ. API_PORT là giá trị được quản lý; giữ cổng đích Railway tương ứng.',
  ]),
  [
    'MANAGEMENT_DATABASE_URL',
    'Configuration database',
    'Cơ sở dữ liệu cấu hình',
    'Keeps recovery available when the match database changes.',
    'Giữ đường khôi phục khi đổi cơ sở dữ liệu trận đấu.',
  ],
  [
    'MANAGEMENT_ENCRYPTION_KEY',
    'External encryption key',
    'Khóa mã hóa bên ngoài',
    'Keep this key outside the configuration database.',
    'Giữ khóa này bên ngoài cơ sở dữ liệu cấu hình.',
  ],
  [
    'MANAGEMENT_ADMIN_TOKEN',
    'Admin transport credential',
    'Mã kết nối quản trị',
    'Only the admin server may use this credential.',
    'Chỉ máy chủ quản trị được dùng mã này.',
  ],
  [
    'MANAGEMENT_API_TOKEN',
    'API service credential',
    'Mã dịch vụ API',
    'Separate service credential; never reuse another service token.',
    'Mã riêng cho dịch vụ; không dùng lại mã dịch vụ khác.',
  ],
  [
    'MANAGEMENT_TELEGRAM_TOKEN',
    'Telegram service credential',
    'Mã dịch vụ Telegram',
    'Separate credential for the Telegram service and its Zalo announcement sender.',
    'Mã riêng cho Telegram và chức năng gửi thông báo Zalo của dịch vụ này.',
  ],
  [
    'MANAGEMENT_ZALO_POLLING_TOKEN',
    'Zalo polling credential',
    'Mã dịch vụ nhận tin Zalo',
    'Separate credential for the polling process.',
    'Mã riêng cho tiến trình kiểm tra tin nhắn.',
  ],
  [
    'MANAGEMENT_ZALO_WEBHOOK_TOKEN',
    'Zalo webhook credential',
    'Mã dịch vụ webhook Zalo',
    'Separate credential for the webhook service.',
    'Mã riêng cho dịch vụ nhận webhook.',
  ],
  [
    'MANAGEMENT_ADMIN_SERVICE_TOKEN',
    'Admin runtime credential',
    'Mã cấu hình máy chủ quản trị',
    'Reads only the admin API connection.',
    'Chỉ đọc kết nối API của máy chủ quản trị.',
  ],
  [
    'MANAGEMENT_API_URL',
    'Admin panel backend URL',
    'Địa chỉ máy chủ bảng quản trị',
    'Stable admin panel backend URL on Railway.',
    'Địa chỉ máy chủ bảng quản trị ổn định trên Railway.',
  ],
  [
    'MANAGEMENT_ALLOWED_ORIGINS',
    'Allowed destinations',
    'Địa chỉ được phép',
    'Explicit origin allowlist, including local development when needed.',
    'Danh sách địa chỉ được phép, gồm địa chỉ phát triển nếu cần.',
  ],
  [
    'MANAGEMENT_ALLOWED_DATABASE_HOSTS',
    'Allowed database hosts',
    'Máy chủ cơ sở dữ liệu được phép',
    'Restricts where candidate database credentials may be sent.',
    'Giới hạn nơi được gửi thông tin kết nối cơ sở dữ liệu.',
  ],
  [
    'MANAGEMENT_PORT',
    'Admin panel backend port',
    'Cổng máy chủ bảng quản trị',
    'Railway must route the admin panel backend domain to this port.',
    'Railway cần trỏ tên miền máy chủ bảng quản trị đến cổng này.',
  ],
  [
    'ZALO_WEBHOOK_PORT',
    'Webhook service port',
    'Cổng dịch vụ webhook',
    'Railway domain target port for the webhook service.',
    'Cổng đích của tên miền webhook trên Railway.',
  ],
  [
    'MANAGEMENT_BOOTSTRAP',
    'Managed startup',
    'Khởi động có quản lý',
    'Enable after the separate admin panel backend is ready.',
    'Bật sau khi máy chủ bảng quản trị riêng đã sẵn sàng.',
  ],
  [
    'NODE_ENV',
    'Runtime environment',
    'Môi trường chạy',
    'Uses one root .env; never selects another file.',
    'Dùng một tệp .env gốc; không chọn tệp khác.',
  ],
  [
    'ADMIN_PASSWORD',
    'Admin login password',
    'Mật khẩu quản trị',
    'Set in the admin panel web app environment, not the bot/backend .env. Used for login recovery.',
    'Đặt trong môi trường web app bảng quản trị, không đặt trong .env bot/backend. Dùng để khôi phục đăng nhập.',
  ],
  [
    'ADMIN_SESSION_SECRET',
    'Admin session signing key',
    'Khóa phiên đăng nhập',
    'Set in the admin panel web app environment, not the bot/backend .env. Changing it signs out existing sessions.',
    'Đặt trong môi trường web app bảng quản trị, không đặt trong .env bot/backend. Đổi khóa sẽ đăng xuất các phiên hiện tại.',
  ],
  [
    'BOT_CONTROLS_LEGACY_API',
    'Legacy API compatibility',
    'Tương thích API cũ',
    'Deployment-only migration switch; keep disabled for managed services.',
    'Chỉ dùng khi chuyển đổi API; tắt trong chế độ có quản lý.',
  ],
  ...[
    'MESSENGER_PAGE_ID',
    'MESSENGER_PAGE_ACCESS_TOKEN',
    'MESSENGER_APP_SECRET',
    'MESSENGER_VERIFY_TOKEN',
    'MESSENGER_GRAPH_API_VERSION',
    'MESSENGER_ADMIN_IDS',
  ].map(key => [
    key,
    key,
    key,
    'Messenger remains deployment managed; this page manages Telegram and Zalo.',
    'Messenger vẫn cấu hình qua triển khai; trang này quản lý Telegram và Zalo.',
  ]),
].map(([key, en, vi, reason, viReason]) => ({
  key,
  secret: /TOKEN|SECRET|KEY|PASSWORD|DATABASE_URL/.test(key),
  label: { en, vi },
  description: { en: reason, vi: viReason },
  reason,
}));
function makeEntry(item) {
  const [key, section, en, vi, type, services, apply, extra = {}] = item;
  return {
    key,
    section,
    label: { en, vi },
    description: {
      en: `Controls ${en.toLowerCase()} for the listed services.`,
      vi: `Điều khiển ${vi.toLowerCase()} cho các dịch vụ được nêu.`,
    },
    type,
    secret: type === 'secret',
    services: [...services],
    apply,
    ...(section === 'Deployment' ? { advanced: true } : {}),
    ...(extra.options ? { options: [...extra.options] } : {}),
    ...(extra.default !== undefined ? { default: extra.default } : {}),
  };
}
const CATALOG = entries.map(makeEntry);
const scope = {
  ADMIN_UI_URL: ['api'],
  WEB_UI_URL: ['api'],
  SUPABASE_URL: ['api'],
  SUPABASE_SERVICE_ROLE_KEY: ['api'],
  SUPABASE_ZALO_STORAGE_BUCKET: ['api'],
  DATABASE_URL: ['api'],
  BOT_COMMAND_PREFIX: ['api'],
  DEBUG_LOGGING: ['api'],
};
for (const entry of CATALOG) {
  if (scope[entry.key]) entry.services = scope[entry.key];
  if (!['API_PORT', 'PORT', 'UI_API_PORT'].includes(entry.key))
    entry.apply = entry.key === 'ADMIN_API_URL' ? 'request' : 'restart';
  if (
    [
      'DATABASE_URL',
      'SUPABASE_URL',
      'SUPABASE_SERVICE_ROLE_KEY',
      'GEMINI_API_KEY',
    ].includes(entry.key)
  )
    entry.advanced = true;
  if (entry.key === 'BOT_COMMAND_PREFIX') {
    entry.section = 'Runtime';
    entry.label = {
      en: 'Legacy API command prefix',
      vi: 'Tiền tố lệnh API cũ',
    };
    entry.description = {
      en: 'Reported by the existing API settings endpoint. Telegram and Zalo slash command names stay unchanged.',
      vi: 'Hiển thị trong cấu hình API hiện có. Tên lệnh Telegram và Zalo không đổi.',
    };
  }
  if (entry.key === 'CHAT_ID')
    entry.description = {
      en: 'Optional Telegram group destination. Private command replies stay in the sender’s chat. Team polls use this destination when set. Leave empty for source-chat routing.',
      vi: 'ID nhóm Telegram tùy chọn. Lệnh trong chat riêng được trả lời tại chat đó. Vote của đội gửi vào nhóm này nếu đã đặt. Để trống để dùng chat gửi lệnh.',
    };
  if (entry.key.endsWith('THREAD_ID'))
    entry.description = {
      en: 'Telegram message_thread_id inside CHAT_ID. Used for group routing, not private command replies. Ignored when CHAT_ID is empty. Leave empty for no topic.',
      vi: 'message_thread_id trong nhóm CHAT_ID. Dùng để gửi vào nhóm, không dùng cho trả lời chat riêng. Bỏ qua khi CHAT_ID trống. Để trống nếu không dùng topic.',
    };
  if (entry.key === 'ZALO_GREETING_TEXT')
    entry.description = {
      en: 'First-contact greeting. Use {name} for the visitor name; leave empty for the default greeting.',
      vi: 'Lời chào lần đầu. Dùng {name} để thêm tên người dùng; để trống để dùng lời chào mặc định.',
    };
}

const CATALOG_MAP = new Map(CATALOG.map(entry => [entry.key, entry]));
function getCatalog() {
  return CATALOG.map(entry => ({
    ...entry,
    label: { ...entry.label },
    description: { ...entry.description },
    services: [...entry.services],
    ...(entry.options ? { options: [...entry.options] } : {}),
  }));
}
function getEntry(key) {
  return CATALOG_MAP.get(key);
}
module.exports = { CATALOG, BOOTSTRAP, getCatalog, getEntry };
